name: Verify Unity License
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Verify Unity License
    runs-on: ubuntu-latest
    steps:
      - name: Unity - Activate
        uses: game-cli/activate@v2.0.0
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }} 
