name: Test Unity Project

on: 
  push:
    branches:
      - main
      - minesweeper
  pull_request:
    branches: 
      - main
      - minesweeper
  workflow_dispatch:

jobs:
  build:
    name: Test the project
    runs-on: ubuntu latest
    steps:
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
